### ISSUE TITLE
아이템 12 질문

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#12]
페이지 75에 보면

**포맷 명시 여부와 상관없이 toString이 반환한 값에 포함된 정보를 얻어올 수 있는 API를 제공하자. 예컨대 PhoneNumber 클래스는 지역코드, 프리픽스, 가입자 번호용 접근자를 제공해야한다.**

라고 나와 있는데,

예를 들어, 지역코드는 PhoneNumber 클래스 내에서만 필요하고 외부에서 이 데이터에 접근할 필요가 없어서, getter를 사용하지 않았는데, toString()을 오버라이드 할 때, 이 데이터도 함께 반환값에 포함되었다는 이유로 getter를 만들어 줘야 하는건가요?

아니면 애초에 toString()을 만들 때, 반환 값에서 제외를 했었어야 했을까요?

**Comment by hongji3354** [comment]
개인적으로 toString에는 모든 필드를 제공해야 한다 생각합니다.

만약 toString으로 제공하지 않는 필드에 의해 오류가 발생한다면, 로그에 해당 기록에 남지 않기 때문에 디버깅이 어렵기 때문입니다.

그리고 toString에서 해당 필드를 사용한다고 해서 꼭 Getter나 파싱할 수 있는 API를 제공해줘야 하는 것은 필수는 아니라 생각합니다.
