### ISSUE TITLE
[아이템 19] protected 메서드에 관해

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#21]
1. p.124에 주의: ListIterator.remove가 선형 시간이 걸리면 이 구현의 성능은 제곱에 비례한다가 무슨말인지 설명좀!
2. List 구현체의 최종 시용자는 removeRange 메서드에 관심이 없다. 그럼에도 이 메서드를 제공한 이유는 단지 하위 클래스에서 부분리스트의 clear 메서드를 고성능으로 만들기 쉽게 하기 위해서다 removeRange 메서드가 없다면 하위 클래스에서 clear 메서드를 호출하면 (제거할 원소 수의) 제곱에 비례해 성능이 느려지거나 부분리스트의 메커니즘을 밑바닥부터 새로 구현해야 했을 것이다. 이것에 대해 설명도요ㅋㅋㅋ

**Comment by DaeAkin** [comment]
```java
    protected void removeRange(int fromIndex, int toIndex) {
        ListIterator<E> it = listIterator(fromIndex);
        for (int i=0, n=toIndex-fromIndex; i<n; i++) {
            it.next();
            it.remove();
        }
    }
```
이 코드는 AbstractList.removeRange() 메서드 입니다. 
이 메서드는 내부적으로 it.remove() 메서드를 호출해서 원소를 삭제하게 됩니다.

여기서 removeRange() 의 시간복잡도는 n입니다.
그런데 만약 remove() 메서드가 시간복잡도가 n으로 구현되어 있다면
결과적으로 removeRange()는 시간복잡도는 n의 제곱이 될 것입니다.

**Comment by DaeAkin** [comment]
2번 답변

**AbstractList.clear()**
```java
public void clear() {
        removeRange(0, size());
    }
```

**AbstractList.removeRange()**
```java
    protected void removeRange(int fromIndex, int toIndex) {
        ListIterator<E> it = listIterator(fromIndex);
        for (int i=0, n=toIndex-fromIndex; i<n; i++) {
            it.next();
            it.remove();
        }
    }
```

AbstractList.clear() 코드를 보면 내부적으로 removeRange()를 이용해서 구현되어 있습니다. 
클라이언트가 list.clear()를 하게 되면 removeRange() 메서드를 호출하게 되는것이죠. 또한 removeRange()는 접근자가 protected 이기 때문에  List 구현체의 최종 사용자는 removeRange() 구현의 관심이 없습니다. 

현재 AbstractList.clear()의 시간복잡도는 O(n) 입니다. 
그런데 제가 새로운 List 구현체를 구현하고있는데, 문득 clear() 메서드의 시간복잡도를 O(1)로 만드는 방법이 떠올랐습니다.
그러면 단지 removeRange() 메서드만 구현을 다시 해주면 됩니다.
이런 메서드들을 hook 메서드라고 합니다.

하지만 이런 의문이 들 수 있습니다. **그냥 clear() 메서드를 오버라이딩 하면 되는것이 아닐까?**
AbstractList 클래스는 추상 골격 구현 클래스로 부분적으로 구현이 되어 있습니다.
그래서 이러한 장점을 계속 유지하기 위해 접근자가 protected이며 hook 메서드인 removeRange() 를 오버라이딩 해야 하는 것입니다.

**Comment by hongji3354** [comment]
하위 클래스에서 AbstractList.removeRange()를 호출하는 예제가 있을까요?

**Comment by DaeAkin** [comment]
대부분의 list 구현체들은 clear()를 오버라이딩 해서 사용하고 있네요.

그나마 AbstracList 추상 골격 클래스를 사용함으로써 이득을 보고 있는 클래스들이 있긴 합니다.
```java

package org.graalvm.compiler.core.common.util;

import java.util.AbstractList;
import java.util.List;
import java.util.RandomAccess;

/**
 * A {@code ReversedList} is a view on an other list with the elements in reverse order.
 *
 * This implementation is made for {@link RandomAccess} lists.
 */
public class ReversedList<T> extends AbstractList<T> implements RandomAccess {
    private final List<T> original;

    public ReversedList(List<T> original) {
        assert original instanceof RandomAccess;
        this.original = original;
    }

    @Override
    public T get(int index) {
        return original.get(original.size() - index - 1);
    }

    @Override
    public int size() {
        return original.size();
    }

    /**
     * Creates a list that is a view on {@code list} in reverse order.
     */
    public static <T> ReversedList<T> reversed(List<T> list) {
        return new ReversedList<>(list);
    }
}

```
이 클래스는 AbstractList의 clear() 와 removeRange()를 그대로 사용하네요.

**Comment by hongji3354** [comment]
찾아보니 ArrayList 안에 있는 SubList가 이러한 구조를 띄고 있네요.

```java
public class Main {
    public static void main(String[] args) {
        List<Integer> list = new ArrayList();

        for (int i=0; i<10; i++){
            list.add(i);
        }

        List<Integer> subList = list.subList(0, 10);
        subList.clear();
    }
}
```

위의 코드에서 clear() 호출시 AbstractList의 clear()을 호출하고 AbstractList의 clear()는 SubList에 재정의되어 있는 removeRange() 메서드를 호출하구요
