### ISSUE TITLE
[아이템 22] 상수 유틸리티 클래스

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#22]
상수 인터페이스
```java
public interafce PhysicalConstants {
  static final double AVOGADROS_NUMBER = 6.022_140_857e23;
  
  static final double BOLTZMANN_CONSTANT = 1.380_648_52e-23;
}
```

상수 유틸리티 클래스
```java
public class PhysicalConstants {
  private PhysicalConstants() {}
  
  public static final double AVOGADROS_NUMBER = 6.022_140_857e23;
  
  public static final double BOLTZMANN_CONSTANT = 1.380_648_52e-23;
}
```

상수 인터페이스를 사용하지 말아야 하는 이유가

> 클래스 내부에서 사용하는 상수는 내부 구현에 해당한다. 따라서 이 내부 구현을 클래스의 API로 노출하는 행위다. 이렇게 사용하면 캡슐화가 깨지며, 클라이언트 코드가 내부 구현에 해당하는 이 상수들에 종속된다. 그래서 다음 릴리스에서 이 상수들은 더 이상 사용하지 않음에도 불구하고 호환성을 위해 지속적으로 제공해줘야 한다. 또한 상수가 final 아니라면 모든 하위 클래스의 동일한 변수명을 사용하고 있는 공간에 인터페이스가 정의한 상수들로 오염이 된다.

인데..

상수 유틸리티 클래스로 구현해도 동일한 단점이 있는 것 같은데 어떻게 생각하시나요?

**Comment by pjhsk113** [comment]
저는 동일한 단점이라 생각하지 않습니다.

보통 클래스 내부에서 사용되는 상수의 경우 private로 선언하여 사용하는데요, 상수 인터페이스의 경우 public static final이기 때문에 내부 구현에 해당하는 상수가 외부로 노출되게 됩니다. 또한, 인터페이스를 구현하는 입장에서 상수만을 담은 인터페이스는 혼란을 줄 수 있습니다. 이는 분명한 단점으로 볼 수 있죠.

반면에, 상수 유틸리티 클래스의 경우 그 목적 자체가 상수 공개에 있다는 점에서 단점이라 보기 어렵다라고 판단했습니다.

저는 위와같이 생각이 드는데 다른 의견이 있다면 이슈남겨주세요!!

**Comment by DaeAkin** [comment]
상수 인터페이스도 public static final 이고
상수 유틸리티 클래스도 public static final 이니까
둘다 모두 상수가 외부로 노출되게 되기 때문에 둘다 똑같다고 생각되거든요 🤔

**Comment by hongji3354** [comment]
상수 유틸리티 클래스로 구현해도 내부 구현이 외부로 노출되고, 캡슐화도 깨지는 게 맞다고 생각합니다.
하지만 저는 아래와 같은 차이점으로 인해 인터페이스 보다는 상수 유틸리티를 사용해야 한다 생각합니다.

1. 상수 클라이언트를 사용하면 클라이언트 입장에서 선택권이 주어집니다. 상수 인터페이스를 상속받는 다면 자신에게 불필요한 상수도 모두 상속을 받아야 하지만, 상수 유틸리티 클래스를 사용하면 자신에게 필요한 상수만 선택할 수 있습니다.
2. 불필요한 관계가 생성되지 않습니다. 인터페이스를 상속받는 다는 것은 결국 인터페이스와 클래스가  연관이 있다는 건데, 유틸리티 클래스를 사용하면 이러한 불필요한 연관을 만들지 않을 수 있습니다.
3. 상수 인터페이스를 사용시에는 해당 상수가 필요하면 무조건 상속을 받아야 하지만 상수 유틸리티 클래스를 그렇지 않습니다. 예를들어 org.springframework.http.MediaType에 상수는 HTTP Media Type과 연관되어 있는 상수로, 주로 Controller에서 response 사용하는 상수입니다. 만약 해당 상수들을 상수 인터페이스에서 사용한다면 모든 Controller 들은 해당 인터페이스를 상속 받아야 하며, Controller의 코드들은 매우 오염될 것이기 때문입니다.
