### ISSUE TITLE
[아이템 24] 정적 멤버 클래스는 바깥 클래스의 private 멤버 에도 접근할 수 있다.

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#23]
p. 146의 정적 멤버 클래스 설명중 바깥 클래스의 private 멤버 에도 접근할 수 있다는 점만 제외하고는 일반 클래스와 똑같다. 라는 내용이 있습니다.

근데 static이 붙을 경우 static 멤버 변수가 아닌 일반 멤버변수는 참조할 수 없으니 틀린 설명이지 않나요?

![Untitled](https://user-images.githubusercontent.com/57903576/110610475-9b627100-81d1-11eb-9df9-b37a7bca40aa.png)

**Comment by pjhsk113** [comment]
![image](https://user-images.githubusercontent.com/32737230/110631372-c9ec4600-81e9-11eb-87b1-41979aa2b590.png)

![image](https://user-images.githubusercontent.com/32737230/110631398-d1135400-81e9-11eb-90eb-e0a339d64295.png)
![image](https://user-images.githubusercontent.com/32737230/110631450-df617000-81e9-11eb-9e28-4cdcd72e69a7.png)


이 차이 아닌가요??

**Comment by DaeAkin** [comment]
장호님 말이 맞는거 같아요. 저도 찾아보니
```java
public class OuterClass {

  private int x = 10;

  private static class InnerClass {
    void test() {
      OuterClass outerClass = new OuterClass();
      outerClass.x = 100;
    }
  }
}
```
여기에 지훈책임님하고 같은 질문이 있네요 https://okky.kr/article/446437

저도 처음에 static이면 당연히 초기화 안됐으니 접근 못하는거 아니야? 라고 생각했네요.

**Comment by hongji3354** [comment]
근데 그냥 member class도 외부 클래스의 모든 멤버에 접근할 수 있으니, 굳이 외 저 말이 있는건지 모르겠네요ㅋㅋㅋ

**Comment by pjhsk113** [comment]
다른 멤버 클래스는 내부 클래스에 해당하고 정적 멤버 클래스는 내부 클래스에 해당하지 않으니 차이를 두고 설명한 거 아닐까요??

`정적 멤버 클래스는 다른 클래스 안에 선언되고, 바깥 클래스의 private  멤버에도 접근할 수 있다는 점만 제외하고는 일반 클래스와 똑같다.` 이 구문에서 정적 멤버 클래스의 비교 대상은 **일반 클래스**니까요.
