### ISSUE TITLE
[아이템 24] 이너클래스보다 중첩클래스가 더 큰 범위인가요?

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#24]
책에 바로 처음에 중첩클래스를 소개할 때 중첩클래스는 4개 있고 그 중 첫번째만 이너클래스다 라고 하는거 보니 
중첩클래스가 더 큰 범위로 이너클래스∈중첩클래스 이겠죠?

**Comment by pjhsk113** [comment]
**첫번째를 제외한** 나머지가 내부(inner) 클래스라는 것을 잘못보신것 같아요!

저도 말씀처럼 중첩 클래스가 조금 더 큰 범위라고 생각해요.

말 그대로 어떤 클래스 안에 중첩되어있는 클래스를 의미하기 때문에 내부 클래스이든 아니든 중첩만 되어 있다면 중첩 클래스로 분류할 수 있습니다.

하지만 이너 클래스는 바깥 클래스의 인스턴스가 없으면 생성할 수 없기 때문에 내부 클래스라고 불리고, 정적 멤버 클래스는 바깥 인스턴스와 별개로 독립적으로 존재할 수 있기 때문에 "내부 클래스에 해당하지 않는다."고 말하고 있죠.

**내부 클래스**와 **내부 클래스에 해당 하지 않는 중첩된 클래스**를 통틀어 중첩 클래스라고 부르는 것을 보니 중첩 클래스가 이너 클래스보다 더 큰 범위에 해당된다고 볼 수 있을 것 같아요!!

**Comment by hongji3354** [comment]
네, 개념상 중첩클래스가 더 큰 범위죠.
왜냐하면 nested class 중 단독으로 인스턴스를 생성할 수 없는 클래스들을 inner class로 지칭하는 거니까요!
