### ISSUE TITLE
[아이템24] 익명 클래스에 대한 예시가 있을까요?

### ISSUE THREAD

**Issue by pjhsk113** [java-starter/ReadingBooks#25]
`오직 비정적인 문맥에서 사용될 때만 바깥 크래스의 인스턴스를 참조할 수 있다. 정적 문맥에서라도 상수 변수 이외의 정적 멤버는 가질 수 없다.` 라는데 무슨말인지 잘 와닿지가 않네요.

혹시 예제 코드가 있을까요?

추가) `익명 클래스를 사용하는 클라이언트는 그 익명 클래스가 상위 타입에서 상속한 멤버 외에는 호출할 수없다.` 이 부분도 이해가 잘안되요ㅠㅠ

**Comment by DaeAkin** [comment]
**비정적인 문맥에서 사용될 때 바깥 클래스 인스턴스를를 참조**
```java
public class TestClass {
    Integer intInstance = 10;

    void doX() {
        new SInterface() {
            @Override
            public void doSometing() {
                //바깥 인스턴스 참조
                System.out.println(intInstance);
            }
        };
    }
}


interface SInterface {
    void doSometing();
}
```

정적 문맥에서라도 상수 변수 이외의 정적 멤버는 가질 수 없다.
```java
public class TestClass {
    // 익명클래스에서 사용 불가
    Integer intInstance = 10;

    static void doX() {
        new SInterface() {
            static final int x = 0;
//            static int y = 0; // 컴파일에러
            @Override
            public void doSometing() {
            }
        };
    }
}

interface SInterface {
    void doSometing();
}
```

**익명 클래스를 사용하는 클라이언트는 그 익명 클래스가 상위 타입에서 상속한 멤버 외에는 호출할 수없다.**
```java
public class TestClass {

    void doX() {
        new SInterface() {
            @Override
            public void doSometing() {
                System.out.println(someInt);
            }
        };
    }
}

interface SInterface extends ParentInterface{
    void doSometing();
}

interface ParentInterface {
    static final int someInt = 10;
}
```

인것 같기도하고... 아닌것 같기도하고 ㅋㅋ

**Comment by hongji3354** [comment]
## 1. 비정적인 문맥에서 사용될 때만 바깥 클래스의 인스턴스를 참조할 수 있다.

비정적인 문맥일 때는 외부 클래스의 인스턴스가 생성되어 있다는 보장이 있기 때문에 외부 클래스의 인스턴스를 참조할 수 있지만 정적인 문맥일 때는 외부 클래스의 인스턴스가 생성되어 있다는 보장이 없기 때문에 외부 클래스의 인스턴스를 참조할 수 없습니다.

## 2. 정적인 문맥에서라도 상수 변수 이외의 정적 멤버는 가질 수 없다.

이거는 제가 적기보다 https://stackoverflow.com/questions/1953530/why-does-java-prohibit-static-fields-in-inner-classes/1954119#1954119를 보시는게 훨씬 이해가 빠를 것 같습니다.ㅠㅠ

## 3. 익명 클래스를 사용하는 클라이언트는 그 익명 클래스가 상위 타입에서 상속한 멤버 외에는 호출할 수 없다.

이건 책에서 의도가 정확히 뭔지 모르겠네요...ㅋㅋ

**Comment by hongji3354** [comment]
근데 **정적인 문맥에서라도 상수 변수 이외의 정적 멤버는 가질 수 없다.** 이거 같은 경우는 애초에 field에 static을 못쓰게 했어야 한다 생각해요.
왜냐하면 static은 인스턴스를 생성하지 않고 사용할 수 있는 건데 이너 클래스는 외부 클래스의 인스턴스를 생성해야 인스턴스를 생성할 수 있기 때문이죠.

**Comment by pjhsk113** [comment]
많은 도움이됬습니다. 감사합니다~
