### ISSUE TITLE
[아이템 26] type parameter와 wild 카드

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#26]
p. 158의 내용중 로 타입 보다 비한정적 와일드카드 타입을 사용하는게 좋다 라는 부분이 있습니다.

근데 비한정적 와일드카드 타입이 아닌 type parameter를 사용해도 상관없을 것이라 생각해는데 어떻게 생각하시나요?

**Comment by DaeAkin** [comment]
비한정적 와일드카드는 **모든 Set을 받아들이면서 동시에 타입안전성을 갖기 위함입니다.**

예를 들어 타입 파라미터인 Set<Object\>로 파라미터를 받게 된다면, Set<Object\>만 받을 수 있습니다.

비한정적 와일드를 카드를 쓰면 실제 타입 매개변수에 관련 없이 Set<Object\> , Set<String\> 전부 받을 수 있다는 장점이 있겠네요.

**Comment by pjhsk113** [comment]
저도 타입 파라미터를 사용해도 괜찮다고 생각해요.

다만, 코드의 전달력이나 의미를 생각해봤을 때 와일드 카드가 조금 더 적절하다고 생각합니다~!!
개인적으로 같은 동작을 하는데 타입 파라미터를 사용한 코드가 와일드 카드에 비해 좀 더 지져분하다고 느껴지네요 ㅎㅎ

아래는 책의 예시로 예제를 만들어 본건데 질문의 의도와 맞는지는 잘 모르겠어여.. 일단 해봄

- 정규 타입 파라미터
![image](https://user-images.githubusercontent.com/32737230/112743960-e56f9300-8fd6-11eb-8db3-6048470ffbb0.png)
![image](https://user-images.githubusercontent.com/32737230/112743967-ef919180-8fd6-11eb-96b6-10d0644b20e3.png)

- 비한정적 와일드 카드
![image](https://user-images.githubusercontent.com/32737230/112743984-0c2dc980-8fd7-11eb-88b2-3acd9a1135e4.png)
![image](https://user-images.githubusercontent.com/32737230/112743990-12bc4100-8fd7-11eb-818c-e5576881d6ee.png)
