### ISSUE TITLE
[아이템 27] @SuppressWarnings 좁은 범위에 대한 toArray 예시에 대해서

### ISSUE THREAD

**Issue by pjhsk113** [java-starter/ReadingBooks#27]
p.162 

@SuppressWarnings는 좁은 범위에 적용하라는 내용을 다루면서 ArrayList의 toArray 메서드를 예시로 드는데요.

메서드 전체에 @SuppressWarnings 애노테이션을 다는 것을 자제하고, 지역 변수를 생성해서 @SuppressWarnings를 좁은 범위로 적용해서 사용하라고 말하고 있습니다

``` java
public <T> T[] toArray(T[] a) {
        if (a.length < size) {
           // 이렇게
           @SuppressWarnings("unchecked") T[] result = (T[]) Arrays.copyOf(elementData, size, a.getClass());
            return rsult;
        }
        System.arraycopy(elementData, 0, a, 0, size);
        if (a.length > size)
            a[size] = null;
        return a;
    }
```

그런데 실제 ArrayList의 toArray 메서드를 보니까 

![image](https://user-images.githubusercontent.com/32737230/112712481-42097a00-8f13-11eb-9fec-4786216b5cb6.png)

메서드에 @SuppressWarnings 애노테이션이 적용되어있네요.

책에서 다루는 예시는 단순히 **범위를 좁혀라**의 예를 들기위해 작성되어진 것이겠죠?

책에서는 저렇게 사용해라! 라고 말하면서 실제 코드에는 적용이 안되있는 것을 보니 

조금 혼란이 오네용.... 다른 분들의 의견을 듣고싶습니다~~~

**Comment by hongji3354** [comment]
책 내용대로 최대한 좁게 쓰는게 좋다 생각해요.
예를들어 예외처리시에서도 단순히 catch문에서 Exception으로 받기보다 최대한 구체 예외를 받아야 예외 발생시 더 정확한 원인을 알 수 있는 것처럼요.

JDK가 최고의 best practice라 하지만, 책 내용보다 보면 잘못된 API도 많다고 하죠ㅋㅋㅋ
그래서 개인적으로 JDK가 무조건 정답이라기 보다 약간 비판적인 관점에서 봐야한다고 생각해요ㅋㅋㅋㅋ

**Comment by DaeAkin** [comment]
지훈님 말씀대로 JDK가 잘못된 것 같네요.

**Comment by pjhsk113** [comment]
그렇군여! 답변 감사합니다
