### ISSUE TITLE
[아이템 28] 매개변수화 타입 가운데 실체화될 수 있는 타입은 List<?>와 Map<?,?> 같은 비한정적 와일드카드 타입 뿐이다.

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#28]
p.166을 보면 **매개변수화 타입 가운데 실체화될 수 있는 타입은 List<?>와 Map<?,?> 같은 비한정적 와일드카드 타입뿐이다** 라는 말이 등장합니다.

일반 매개변수화 타입은 결국 런타임시 소거되는 것이 맞는데 비한정적 와일드카드는 소거가 안되는 건가요?

PS. 공변과 비공변의 깔끔한 설명도 부탁드립니다!

**Comment by hongji3354** [comment]
생각해보니 와일드 카드는 소거가 아닌 Object로 치환이 되네요.
왜냐하면 와일드 카드의 목적이 제네릭 타입이 어떤게 들어오던 상관이 없으니깐요

**Comment by DaeAkin** [comment]
S extends T 일 경우를 가정.

공변성(covariance) : S와 T 사이의 서브타입 관계가 그대로 유지된다. 이 경우 해당 위치에서 서브타입인 S가 슈퍼타입인 T 대신 사용될 수 있다. 우리가 흔히 이야기하는 리스코프 치환 원칙은 공변성과 관련된 원칙이라고 생각하면 된다.

비공변성(invariance) : S와 T 사이에는 아무런 관계가 존재하지 않는다. 따라서 S대신 T를 사용하거나 대신 S를 사용할 수 없다..

**Comment by hongji3354** [comment]
@DaeAkin 
음 근데 S extends T는 제네릭에서만 사용할 수 있는 개념이고 배열에서는 사용불가한 개념이니 다른 예시를 드는게 좋을 것 같은데 어떤가요?!!

**Comment by DaeAkin** [comment]
책의 코드 처럼
```java
Object[] objectArray = new Long[1];
```
선언은 부모타입인 Object 했지만, 생성되는 객체는 하위타입인 Long인 상황을 공변성이라고 하고,

```java
List<Object> ol = new ArrayList<Object>
```
위에처럼 List<Object\> 타입은 무조건 List<Object\>만 받을 수 있고 List<String\> 등은 받지 못하는 상황을 비공성이라고 하지 않을까요

**Comment by pjhsk113** [comment]
``` java
public class Human {}
public class Man extends Human{}
public class Woman extends Human{}
```

다음과 같은 계층 구조가 있다고 가정하겠습니다.

먼저, 공변이란 함께 변하는 성질을 말합니다. 
위의 계층 구조가 공변이라면, 인간(Human)의 신체구조가 변경되었을 때
남자(Man)나 여자(Woman)의 신체구조도 함께 변경될 것입니다. 즉, 상속 관계가 유지된다는 뜻이죠.

배열은 **공변** 성질을 가지고 있기 때문에 상속관계가 유지됩니다. 
``` java
// 문제 없음.
Man[] man = new Man[1];
Human[] humans = man; 
```
<br>

반면에 제네릭은 비공변 성질을 가지고 있기 때문에 컴파일 에러가 발생합니다.
```java
List<Man> man = new ArrayList<>();
List<Human> humans = man;  // 컴파일 에러
```
`Human`과 `Man`은 상속관계지만 `List<Human>`과 `List<Man>`은 상속 관계가 아닙니다.

이처럼 제네릭이 비공변 성질을 가지는 이유는 제네릭의 소거 때문입니다.

런타임에는 원소 타입이 소거되어 `List`만 가지고 있습니다. 따라서 Human 타입인지 Man 타입인지 알 방법이 없습니다. 
(런타임시 타입 안전하지 않음)

따라서 비공변 성질을 이용해 컴파일 타임에 타입 안전성을 보장하는 것입니다.

제네릭을 공변처럼 사용하고 싶다면 다음과 같이 한정적 와일드 카드 타입이나 을 사용하면 됩니다.

```java
// 문제 없음
List<Man> man = new ArrayList<>();
List<? extends Human> humans = man; 
```

**Comment by hongji3354** [comment]
두 분 다 잘 설명 해주셨네요ㅋㅋㅋㅋ
혹시나 개념 정리하는데 도움이 될 것 같아서 올려요ㅋㅋㅋ

모던 랭귀지는 타입바운드 개념을 제공하는데 크게 3가지가 제공 된다고 합니다.
1. 불공변성(Invariant)
 - 상속관계에 상관없이, 자기 타입만 허용하는 것
2. 공변성(covariant)
 - 타입 생성자에게 리스코프 치환 법칙을 허용하는 것
3. 반공변성(contravariant)
 - 자기 자신과 부모 객체만 허용하는 것
