### ISSUE TITLE
[아이템 28] 힙 오염 예제 코드

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#29]
힙 오염의 개념이 매개 변수화된 타입의 변수가 매개 변수화 되지 않은 타입의 변수를 참조할 때 발생한 다는 것은 이해를 했습니다.

아마 이게 소거되는 제네릭이 있고 소거되지 않는 제네릭이 있어서 이러한 문제가 발생할 수 있는 것 같네요

개념은 이해가 되는데 구체적인 코드가 궁금합니다!!!

개념을 상세히 더 설명해 주시면 떙큐!!

**Comment by DaeAkin** [comment]
http://kimalam.blogspot.com/2019/09/java-heap-pollution.html

**Comment by hongji3354** [comment]
오....
이게 컴파일러가 잡아줄줄 알았는데 되는군요ㅋㅋㅋ

**Comment by pjhsk113** [comment]
좋은 예제를 가져오셨군요 감사합니다~!!
