### ISSUE TITLE
[아이템 29] 비검사 형변환이 안전한 경우

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#30]
아이템 29에서 예전에 만들었던 Stack을 제너릭으로 변경하는 예제 중에서
```java
elements = (E[]) new Object[DEFAULT_INITIAL_CAPACITY];
```
해결법1이 이 방법 이였는데요, 그 내용 중에
> 컴파일러는 이 프로그램이 타입 안전한지 증명할 방법이 없지만 우리는 할 수 있다. 따라서 이 비검사 형변환 프로그램의 타입 안전성을 해치지 않음을 우리가 스스로 확인해야 한다. 문제의 배열 elements는 private 필드에 저장되고, 클라이언트로 반환되거나 다른 메서드에 전달되는 일이 전혀 없다. push 메서드를 통해 배열에 저장되는 원소의 타입은 항상 E다. 따라서 이 비검사 형변환은 확실히 안전하다. 

즉 비검사 형변환이 안전하지 확인하려면
- 변수의 접근자가 private인지?
- 클라이언트로 반환되는지?
- 다른 메서드가 사용하는지? 
총 3개 확인해야 된다는 건데, 

elements의 접근자가 public이여도 클라이언트가 직접 접근해도 타입을 알 수 있으니, 형변환에 안전할 것 같고,
elements의 배열이 클라이언트로 반환되어도 타입을 알 수 있으니  형변환에 알 수 있을 것 같고,
다른 메서드가 elements 배열을 사용해도 타입을 이미 알고 있으니, 상관없지 않나요..

**Comment by pjhsk113** [comment]
- 변수의 접근자가 private인지?
- 클라이언트로 반환되는지?
- 다른 메서드가 사용하는지?

문맥상 위의 조건들을 꼭 만족해야만 비검사 형변환이 안전하다는게 아니고
책에서 예로든 Stack에서 비검사 형변환이 **왜 확실히 안전한가**에 대해 설명한 듯 싶습니다.

우리는 타입 안전성을 해치지 않는다고 판단을 내렸을 때 비검사 경고를 제거합니다.
컴파일러가 못하는 일을 스스로 검증하고 제거하는 것이죠.

예를 들어, 클라이언트로 반환되거나 다른 메서드가 사용해도 타입 안전성이 보장된다면 비검사 경고를 제거해도 된다는뜻입니다.

저는 비검사 형변환이 안전하지 확인하는 방법은 상대적인 것이라는 생각이드네요!

**Comment by hongji3354** [comment]
물론 동현씨가 말한데로 해도 상관이 없을 거라 생각합니다.
다만 누군가가 만든 API는 불특정 다수가 사용할 것인데, 해당 API를 사용하는 불특정 다수가 해당 API를 만든 사람의 의중을 전부를 알 수 없음으로, 최대한 방어적으로 작성하는게 맞다고 생각합니다.

그렇게 방어적으로 작성하기 위해서 제시는 방법이 동현씨가 말하는 것들이라 생각하구요
