### ISSUE TITLE
[아이템31] 생산자와 소비자 역할을 동시에 하는 매개변수

### ISSUE THREAD

**Issue by pjhsk113** [java-starter/ReadingBooks#32]
p.183 

> *입력 매개변수가 생산자와 소비자 역할을 동시에 한다면 와일드카드 타입을 써도 좋을 게 없다.*

생산자와 소비자 역할을 동시에 하는 매개변수에 해당하는 예제가 있을까요?

**Comment by DaeAkin** [comment]
그건 구현하기 나름 아닐까요. 

넘어온 인자가, 메서드 안에서 어떤 역할을 하게끔 코드를 작성하냐에 따라 케바케일듯..

**Comment by hongji3354** [comment]
생산자라면 <? extends T> : T를 포함한 하위 타입이 가능
소비자라면 <? super T> : T를 포함한 상위 타입이 가능

결국 생산자이면서 소비자이면 T만 사용하는 것이기 때문에, 일반적으로 제네릭 사용하는 방법과 동일하다 생각됩니다.

**Comment by DaeAkin** [comment]
```java
class TestStack<E> extends Stack<E>{

    public Collection<E> doSomething(Collection<E> src) {
        Collection<E> dst = new ArrayList<>();

        for (E e : src) {
            addElement(e); // consumer 역할
        }

        while (!isEmpty())
            dst.add(pop()); // producer 역할

        return dst;
    }

}
```
