### ISSUE TITLE
[아이템 31] 한정적 와일드카드를 사용한 max() 메서드 두번째 질문

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#33]
`public static <E extends Comparable<E>> E max(List<E> list)` 

이 메서드의 리턴타입은 Comparable를  상속한 E 타입이여야 할까요? 
제거해도 잘 작동되더라구요

**Comment by hongji3354** [comment]
혹시 E에 어떤 요소를 넣으셨나요?

아래 예제 코드 처럼 Comparable를 상속받지 않는 클래스를 요소로 하면 컴파일 에러가 발생하거든요!

```java
public class Main {
    public static void main(String[] args) {
        List<Inner> list = new ArrayList<>();
        max(list);
    }

    public static <E extends Comparable<E>> E max(List<E> list){
        return (E) list;
    }

    public class Inner {

    }
}
```
![image](https://user-images.githubusercontent.com/57903576/115051947-53ddac00-9f18-11eb-905d-0ebec44c77a8.png)
