### ISSUE TITLE
[아이템 38] 확장한 타입과 기반 타입

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#38]
아이템38 바로 첫장에 보면

> 사실 대부분 상황에서 열거 타입을 확장하는건 좋지 않은 생각이다. 확장한 타입의 원소는 기반 타입의 원소로 취급하지만 그 반대는 성립하지 않는다면 이상하지 않은가! 

에서 확장한 타입과 기반 타입에 설명좀 더 해주세여

**Comment by hongji3354** [comment]
이건 객체지향에 상속관계를 생각해 보면 어떨까요?

예를들어 Human이라는 클래스가 있고 Human을 상속받아서 민동현 클래스를 만든다고 생각해 보죠.

이때 책의 내용데로 확장한 타입의 원소는 기반 타입의 원소로 취급된다를 위의 클래스 구조로 풀면 **민동현은 사람이다.**가 되죠

이제 저 말을 반대로 해보면  **사람은 민동현이다.**가 되기 때문에 성립이 안되는 거죠.

사실 제가 적어놓고 맞는지 모르겠네요

열심히 피드백 올려주시죠ㅋㅋㅋㅋ

**Comment by DaeAkin** [comment]
그런데 책 내용 보면

Enum 타입은 성립이 안되는데,
클래스는 성립이 되야되는게 아니예요?

**Comment by hongji3354** [comment]
맞아요ㅋㅋㅋ
저건 제가 그냥 생각난 상속관계 적다보니 이상해 졌네요.
