### ISSUE TITLE
[아이템 38] 타입 안전 열거 패턴의 확장

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#39]
책에서 타입 안전 열거 패턴은 열거한 값들을 그대로 가져온 다음 값을 더 추가하여 다른 목적으로 쓸 수 있는 반면, 열거 타입은 그렇게 할 수 없다고 합니다.

이제 대한 예제가 있으면 좋을 것 같습니다.

**Comment by DaeAkin** [comment]
타입 안전 열거 패턴은, 클래스를 이용하기 때문에 확장이 가능합니다.
열거타입은 확장 자체가 불가능 합니다.

**타입 안전 열거 패턴**
``` java
public class DSymbolType{
  private final String type;
  private DSymbolType(String type){
    this.type = type;
  }
  public String toString(){
    return type;
  }
  public static final DSymbolType Terminal = new DSymbolType("Terminal");
  public static final DSymbolType Process = new DSymbolType("Process");
  public static final DSymbolType Decision = new DSymbolType("Decision");
}
```

**열거 타입**
```java
// extends가 허용 되지 않음.
public enum TestEnum extends TestClass {
}

class TestClass {}
```
열거 타입을 확장할 수 없는 이유는 열거타입들은 이미 열거타입의 기능을 제공하는 Enum<T> 을 상속받았기 때문

**Comment by hongji3354** [comment]
@DaeAkin DSymbolType의 생성자의 접근제어자가 private 이기 때문에 상속이 안되지 않나요?

**Comment by DaeAkin** [comment]
아 복붙하느라 생성자가 private인거 못봣네여 ㅋㅋ 

암튼 클래스랑 enum의 특징 차이 때문인거같네여
