### ISSUE TITLE
[아이템 41] 마커 인터페이스는 적용 대상을 더 정밀하게 지정할 수 있다.

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#40]
p.249를 보면 **마커 인터페이스가 나은 점 두 번째는 적용 대상을 더 정밀하게 지정할 수 있다는 것이다.** 라는 말이 있습니다.

근데 마커 인터페이스는 클래스 레벨에서만 사용가능 하지만, 마커 어노테이션은 다양한 대상에 적용이 가능하고 세부 대상도 한정이 가능하기 때문에 범용적으로 봤을 때 틀린 설명이라 생각하는데 어떻게 상각하시나요?

**Comment by DaeAkin** [comment]
만약에 그 Marker에 제약사항을 주고 싶다고 가정을하면,

마커 어노테이션으로 만들어 졌다면, 그 마커 어노테이션을 사용하고 있는 모든 곳에 영향을 받지만

마커 인터페이스를 사용하면 개발자가 마음대로 커스텀할 수 있어서 더 정밀하다고 하네요.

https://stackoverflow.com/questions/26271786/marker-annotation-vs-marker-interface

**Comment by hoy172** [comment]
마커 어노테이션은 타겟으로 지정한 클래스나 메서드등 에 해당되면 다 마킹할 수 있지만
인터페이스로 마킹하게 되면 해당 인터페이스의 구현체들에게만 마킹 할 수있어서 
특정 타입이외는 마킹하지 못하게 제약을 걸수 있어 더 정밀하다고 한 뜻아닐까요?

**Comment by pjhsk113** [comment]
두 번째 장점은 **타입을 대상**으로 한 마커 인터페이스의 장점을 말하고 있어요. 그 마커를 **어떤 타입에 부착할 수 있냐**가 두 번째 장점에서 말하고 있는 정밀함의 의미라고 생각합니다.

마커 인터페이스는 클래스와 인터페이스만이 구현하거나 확장할 수 있습니다. 반면에 마커 애너테이션은 모든 타입에(클래스, 인터페이스, 열거타입, 애너테이션)에 부착할 수 있죠.

다양한 타입에 부착이 가능하다는 건 그만큼 더 넓은 범위를 포괄하고 있다는 의미이고, 클래스와 인터페이스에만 부착할 수 있는 인터페이스에 비해 정밀함이 떨어진다는 걸 말하고 있는 것 같습니다.

P.S.

지훈님이 생각하시는 `다양한 대상에 적용이 가능하고 세부 대상도 한정이 가능하다`는 어떤 부분을 말하시는 건지 궁금해요.
