### ISSUE TITLE
[item43] 한정적 인스턴스 메서드 참조와 비한정적 인스턴스 메서드 참조

### ISSUE THREAD

**Issue by pjhsk113** [java-starter/ReadingBooks#41]
p.260 ~ 261 사이에 메서드 참조 유형 5가지에 대해 설명이 나오는데

이 중 한정적, 비한정적 인스턴스 메서드에 대한 설명이 부족해요...!!!!!

이해하기 쉽도록 설명 부탁드리겠습니다.

**Comment by DaeAkin** [comment]
옙

**Comment by hongji3354** [comment]
@pjhsk113 
아직 올리지는 않았지만 제가 정리한 거인뎅 도움이 됐으면 하네여ㅋㅋ

## 한정적 인스턴스 메서드
수신 객체(receiving object;  참조 대상 인스턴스)를 특정하는 참조이다.
정적 메서드 참조 처럼 함수 객체가 받는 인수와 참조되는 메서드가 받는 인수가 동일하다.
코드를 보면 수신 객체는 `Instant then`로 특정되어 있으며, 함수 객체가 받는 인수인 time과 참조되는 메서드인 isAfter의 인수가 동일하다.
```java
//method reference
Instant.now::isAfter

//lambda
Instant then = Inatant.now();
time -> then.isAfter(time)
```

## 비한정적 인스턴스 메서드

수신 객체(receiving object; 참조 대상 인스턴스)를 특정하지 않는 참조이다.
비한정적 참조에서는 함수 객체를 적용하는 시점에 수신객체를 알려준다. 
```java
//method reference
String::toLowerCase

//lambda
str -> str.toLowerCase()
```

수신 객체 전달용 매개변수가 매개변수 목록의 첫 번째로 추가되며, 그 뒤로는 참조되는 메서드 선언에 정의된 매개변수들이 뒤따른다. 비한정적 참조는 주로 스트림 파이프라인에서의 매핑과 필터 함수에 쓰인다.
예를들어 비한정적 인스턴스 메서드 참조를 풀면 아래와 같은 구조가 된다.
참조되는 메서드 선언에 정의된 매개변수가 없기 때문에, 수신 객체 전달용 매개변수만 추가 되었다.
```java
//수신 객체 전달용 매개변수가 추가된다.
toLowerCase(String str)
```

**Comment by hongji3354** [comment]
@pjhsk113 아직 이해가 안되신건가요?ㅋㅋㅋㅋ

**Comment by DaeAkin** [comment]
저도 이해 안됐음ㅋㅋ

**Comment by hongji3354** [comment]
음.... 어떤 부분이 이해 안가신건가요?

**Comment by DaeAkin** [comment]
일욜날 회의때 한번 설명좀 해주세요
