### ISSUE TITLE
[아이템 42] 람다를 사용할 수 없을 때 예제

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#42]
책의 마지막 부분을 보면 다음과 같은 문장이 있습니다.

- 추상 클래스의 인스턴스를 만들 때 람다를 쓸 수 없다
- 여러 개인 인터페이스의 인스턴스를 만들 때도 익명 클래스를 쓸 수 있다.

예제 코드가 있으면 명확히 이해가 될 것 같아요!

**Comment by DaeAkin** [comment]
## 추상 클래스의 인스턴스를 만들 때 람다를 쓸 수 없다
``` java
public class Main {
     public static void main(String[] args) {
          EffectiveTest effectiveTest
                  = () -> System.out.println("hi");
      }
}

interface EffectiveTest {
     void doSomething();
}
```
위에 코드는 되지만

```java
public class Main {
     public static void main(String[] args) {
          EffectiveTest effectiveTest
                  = () -> System.out.println("hi");
      }
}

abstract class EffectiveTest {
     abstract void doSomething();
}
```

 이 코드는 안됩니다
<img width="421" alt="스크린샷 2021-06-05 오후 1 06 07" src="https://user-images.githubusercontent.com/27226273/120879511-cc024d00-c5fe-11eb-980e-4e4a1fd7d893.png">

## 여러 개인 인터페이스의 인스턴스를 만들 때도 익명 클래스를 쓸 수 있다

익명클래스 대신 람다를 사용하려면
 **구현되지 않은 추상메서드 선언이 1개일 때만 가능합니다.**
그러므로 추상 메서드가 여러 개인 인터페이스라면, 람다를 사용하지 못하고 익명클래스를 사용해야 합니다.
