### ISSUE TITLE
[아이템 45] 스트림은 주의해서 사용하라

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#44]
p. 269를 보면 스트림 API는 메서드 연쇄를 지원하는 플루언트 API(fluent API)다. 라는 설명이 있습니다.

플루언트 API에 대해 찾아보니 메서드 체이닝에 + 알파를 한 느낌인데 추가적인 설명이 필요할 것 같아요

**Comment by pjhsk113** [comment]
플루언트 API는 코드를 읽기 쉽고 사용하기 쉽도록 메서드 체이닝 기반으로 설계된 객체 지향 API입니다. 메서드 체이닝으로 다음에 수행할 수 있는 작업들을 안내해서 사용자가 좀 더 사용하기 쉽도록 하는 것이 목적입니다.

자바에서는 대표적으로 LocalDateTime에서 플루언트 API를 제공하죠.
``` java
// LocalDateTime Fluent API 예시
LocalDateTime.now().withYear(2021).minusYears(2).getYear();
```

<br/>

대략적인 구조를 만들어보면 이런식으로 만들 수 있어요
```java
public interface MyFluent {
    // something
}

public class Start implements MyFluent {
    DoSecond doFirst() {
        return null;
    }
}

public interface DoSecond extends MyFluent {
    FinishWith doSecond();
}

public interface FinishWith extends MyFluent {
    void finishOne();
    void finishTwo();
}
```

```java
public static void main(String[] args) {
    new Start().doFirst().doSecond().finishOne();
}
```

[참고 자료](https://stackoverflow.com/questions/33632303/how-to-test-a-java-fluent-api)
<br/>

여기에 간단한 예시가 있습니다. 참고해보시면 좋을 것 같아요
[Design a Fluent API in Java](https://dzone.com/articles/java-fluent-api-design)
