### ISSUE TITLE
[item46] 다운스트림의 개념

### ISSUE THREAD

**Issue by pjhsk113** [java-starter/ReadingBooks#45]
p.282

다운스트림이라는 개념이 나오는데 정확히 뭘 의미하는건지 헷갈립니다.

수집기 안에 정의되는 또 다른 수집기를 말하는 것 같은데....

``` java
// ex
words.collect(groupingBy(String::toLowerCase, toSet()));
```

<br/>

> 다운스트림 수집기의 역할은 해당 카테고리의 원소들을 담은 스트림으로부터 값을 생성하는 일

책에 나와있는 이 말이 헷갈리네요..  값을 생성한다?? 수집기는 값을 모으는거 아닌가 해서요..

`원소들을 담은 스트림으로부터 값을 생성하는 일`  <--- 무슨 의미일까요?

**Comment by hongji3354** [comment]
수집기의 역할이 기존 스트림 원소로 부터 새로운 컬렉션을 만들어 내는 역할이니 `원소들을 담은 스트림으로부터 값을 생성하는 일`이라는 말이 사용되지 않았나 싶습니다.
하지만 개인적으로 `원소들을 담은 스트림으로부터 원소를 가져와서 컬렉션을 만든다`라는 설명이 더 맞지 않나 싶습니다.

그리고 downstream은 실제 예제 코드로 보는게 더 이해가 빠르실 것 같아서 추가하였습니다.

groupingBy(classifier) 사용시 기본적으로 카테고리별로 모아놓은 Map을 return 합니다.
해당 Map에서 value의 자료구조는 ArrayList를 사용하는데 downstream을 사용해서 value에 사용되는 자료구조를 변경할 수 있습니다.

예를들어 다음코드에서는 downstream을 LinkedList로 지정함에 따라 value의 자료구조가 ArrayList가 아닌 LinkedList가 됩니다.

```java
public static void main(String[] args) {

        String[] word = new String[]{"abc","cba","bac","bcd","dcb","cbd","def","edf","fed"};

        Arrays.stream(word)
                .collect(Collectors.groupingBy(s -> alphabetize(s), Collectors.toCollection(LinkedList::new)));
        
    }

    private static String alphabetize(String s) {
        char[] a = s.toCharArray();
        Arrays.sort(a);
        return new String(a);
    }
```

![image](https://user-images.githubusercontent.com/57903576/122483945-a4ec4800-d00e-11eb-84a6-cd669fae5dc4.png)
