### ISSUE TITLE
[DDD Start] 게시글과 첨부파일은 하나의 애그리거트 일까?

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#46]
DDD Start의 p.74를 보면 애그리거트 경계에 대한 정의를 다음과 같이 설명하고 있습니다.
> 경계를 설정할 때 기본이 되는 것은 도메인 규칙과 요구사항이다. 도메인 규칙에 따라 함께 생성되는 구성요소는 한 애그리거트에 속할 가능성이 높다.

위와 같은 관점에서 본다면 게시글과 첨부파일도 하나의 애그리거트일까요?
왜냐하면 게시글 삭제시 첨부파일도 같이 삭제되어야 하니 하나의 애그리거트라 생각하는데, 확신이 안드네요

**Comment by DaeAkin** [comment]
도메인 성격에 다를 것 같아요.

- 게시판을 사용할 때 첨부파일이 필수인지?
- 댓글에도 첨부파일을 달 수 있을 경우, 게시판에서 사용한 첨부파일 도메인을 같이 쓰는지? 아니면 댓글첨부파일 도메인을 만들어서 따로 쓰는지?


이런걸 종합해서 생각해서 애그리거트 경계를 정해야 할 것 같네요.

게시글과 첨부파일만 관점에서 본다면 변경되는 빈도가 높기 때문에 저라면  한 애그리거트에 속하게 만들 것 같아요
