### ISSUE TITLE
[item50] clone 메서드 사용에 대한 예시

### ISSUE THREAD

**Issue by pjhsk113** [java-starter/ReadingBooks#47]
p.304

Date의 clone 메서드를 사용하지 않은 이유를 설명하는데 이해안가는 부분이 있어서 질문남깁니당

첫 번째 질문.
> Date는 final이 아니므로 clone이 Date가 정의한 게 아닐 수 있다.

무슨 의미일까요? 
final 클래스가 아니기 때문에 확장할 수 있고 Date를 확장한 어떤 클래스의 clone일 수 있다? 라는 건지...

<br/>

두 번째 질문.
> 예컨데 이 하위 클래스는 start와 end 필드 참조르르 private 정적 리스트에 담아뒀다가 공격자에게 리스트로 접근하는 길을 열어줄 수도 있다.

글로 봐서는 잘 안그려지는데 위 예시를 코드로 보고싶어요

**Comment by DaeAkin** [comment]
```java
public class Main {

     public static void main(String[] args) {
         MaliciousDate someDate = new MaliciousDate();
         Date copyOfMaliciousDate = someDate;
         Date anotherDate = (Date)copyOfMaliciousDate.clone();
     }

}
 class MaliciousDate extends Date {

     @Override
     public Object clone() {
         System.out.println("MailciousDate");
         return super.clone();
     }
 }
```

**결과**
```
MailciousDate
```

copyOfMaliciousDate 변수는 Date 타입이고, clone() 메서드를 호출하면 Date 객체가 나옵니다.
하지만 copyOfMaliciousDate의 clone 메서드를 호출하게 되면 MaliciousDate 클래스의 clone() 메서드가 호출됩니다.

그래서 MaliciousDate 클래스 내부에 start와 end 필드 참조를 공격자에게 접근하게 만들 수도 있고 그러네요.

이런 상황을 방지하려면 Date 클래스가 final 이여서 확장 불가능한 클래스면 ㄱㅊ아질듯
