### ISSUE TITLE
[아이템 69] 

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#48]
내용 보면 

> JVM은 배열에 접근할 때마다 경계를 넘지 않는지 검사하는데, 일반적인 반복문도 배열 경계에 도달하면 종료한다.
>따라서 이 검사를 반복문에도 명시하면 같은 일이 중복되므로 하나를 생략한 것이다.

라고 있는데 `하나를 생략한 것이다` 가 이해가 안가요

**Comment by pjhsk113** [comment]
```java
// 예외를 잘못 사용한 예
try {
  int i = 0;
  while(true) {
    range[i++].climb();
  }
} catch (ArrayIndexOutOfBoundsException e) {
}
```

위의 코드를 작성한 이유를 설명하는 구문입니다.

일반적인 반복문을 사용했을 경우 `JVM에서 배열에 접근할 때 수행되는 경계 검사`와 `일반적인 반복문에서 수행하는 경계 검사`가 중복으로 수행된다라고 생각했고(잘못된 추론)

일반적인 반복문에서 수행하는 경계 검사를 생략하기 위해 위와 같은 코드를 작성했다. 라는 의미인거 같아요

즉, "잘못된 추론 때문에 저런 코드를 작성한 것이다." 를 설명하기 위한 빌드업이라고 보시면 되것습니다.
