### ISSUE TITLE
[Item90] 프록시 직렬화 패턴의 장점

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#51]
장점 두 가지가 의문이네요
> 방어적 복사처럼, 직렬화 프록시 패턴은 가짜 바이트 스트림 공격과 내부 필드 탈취 공격을 프록시 수준에서 차단해준다.

차단 못하지 않나요?
>직렬화 프록시는 Period 필드를 final로 선언해도 되므로 Period 클래스를 진정한 불변으로 만들 수 있다. 

fianl 붙였다고 불변이 아닐 수 있잖아요.
Period의 내부상태를 바꿔버리면..

**Comment by pjhsk113** [comment]
### 1번 질문

> 방어적 복사처럼, 직렬화 프록시 패턴은 가짜 바이트 스트림 공격과 내부 필드 탈취 공격을 프록시 수준에서 차단해준다.

먼저, 가짜 바이트 스트림 공격은 readObject() 메서드에서 불변식을 만족하는지 검사함으로써 방어할 수 있어요.
```java
private void readObject(ObjectInputStream s) throws IOException, ClassNotFoundException {
    s.defaultReadObject();
    
    // 불변식을 만족하는지 검사한다.
    if(start.compareTo(end) > 0) {
       throw new InvalidObjectException(start + "가 " + end + "보다 늦다.");
    }
}
```

직렬화 프록시에서는 애초에 바깥 클래스(Period)의 바이트 스트림을 조작하려하면InvalidObjectException이 발생합니다.

```java
/**
 * readObject는 Serializable을 구현한 모든 타입을 생성할 수 있고, 그 타입들 안의 모든 코드도 수행할 수 있다.
 * readObject를 통해 불변식을 훼손하려 하면 InvalidObjectException을 던진다.
 */
private void readObject(ObjectInputStream stream) throws InvalidObjectException {
    throw new InvalidObjectException("프록시가 필요합니다.");
}
```

따라서 직렬화 프록시에서 가짜 바이트 스트림 공격을 방어하고 있다고 볼 수 있죠.

내부 필드 탈취 공격 또한 방어 방법이 아이템88에 소개 되어 있습니다.

아이템88의 예제를 보면
```java
private void readObject(ObjectInputStream s) throws IOException, ClassNotFoundException {
    s.defaultReadObject();

    // 가변 요소들을 방어적으로 복사한다.
    start = new Date(start.getTime());
    end = new Date(end.getTime());

    // 불변식을 만족하는지 검사한다.
    if (start.compareto(end) > 0) {
        throw new InvalidObjectException(start + " after " + end);
    }
}
```

다음과 같이 readObject() 메서드에 private 가변 요소들을 방어적으로 복사하는 코드를 넣은 후에 불변식 검사 로직을 수행하는 것으로 내부 필드 탈취를 방어하고 있습니다.

내부 필드 탈취 공격은 Period를 역직렬화 한 후 내부 필드의 참조를 훔쳐 불변식을 깨트리는 공격 방법입니다.

하지만 직렬화 프록시의 readObject() 메서드는 InvalidObjectException을 발생시키니, 직접 Period로 역직렬화를 할 수 없고 무조건 직렬화 프록시를 거쳐야만 역직렬화가 가능합니다.

그렇기 때문에 내부 필드 탈취 공격에도 방어가 되는 것이라고 볼 수 있죠!

### 2번 질문

> 직렬화 프록시는 Period 필드를 final로 선언해도 되므로 Period 클래스를 진정한 불변으로 만들 수 있다.

저도 이 부분이 조금 헷갈리네요. 동현씨 말대로 내부 상태를 조작해버리면 불변이 깨지는데..

아무래도 직렬화/역직렬화 시 불변이 깨지지 않음을 보장하는 자바 직렬화 시스템에서의 불변을 말하는 것 같네요.
