### ISSUE TITLE
base62 변환법

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#52]
62진법에서는 10은 a로 61은 Z로 대응시키는데,

62진법에서 'a'는 1010을 나타내고 'Z'는 6110을 나타낸다는 말이 이해가 안가요.

135p입니당

**Comment by jiseok-choi** [comment]
62진법에서 10은 'a' 는 10 을 나타내고 'Z'는 61 로 대응시키는 것이 맞습니다.

질문에 대해 답변을 보다 정확히 하기 위해 출판사에 

내용확인과 원문 비교를 요청한 결과 오타라고 답변을 받았습니다.

다음은 출판사 쪽 응답 내용입니다.

=============================================

안녕하세요, 인사이트 출판사 XXX입니다. 

문의하신 내용은 오탈자로, 수정한 내용 정오표에 반영해두겠습니다. 

확인해주셔서 감사합니다. 


수정 전: 따라서 62진법에서 ‘a’는 1010을 나타내고, ‘Z’는 6110을 나타낸다.
수정 후: 따라서 62진법에서 ‘a’는 10을 나타내고, ‘Z’는 61을 나타낸다.
원문(141쪽): where ‘a’ stands for 10, ‘Z’ stands for 61, etc. 

==============================================
