### ISSUE TITLE
p.103의 그림 4.12 잠겨진 레코드 읽기

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#53]
p.103의 그림 4.12 잠겨진 레코드 읽기는 격리레벨이 READ_COMMIT, REPEATABLE_READ, SERIALIZABLE인 경우에만 해당하고 READ_UNCOMMIT 일 경우에는 아니지 않나요?

**Comment by pjhsk113** [comment]
SERIALIZABLE은 읽기 잠금이 있지 않나요?

READ_UNCOMMIT은 언두로그를 읽지 않고 버퍼 풀이나 데이터 파일을 읽으니까
말씀하신대로 4.12 그림은  READ_COMMIT, REPEATABLE_READ만 해당하는 것 같네욤

**Comment by jiseok-choi** [comment]
맞습니다! READ UNCOMMITTED 격리레벨은 기본적으로 버퍼 풀과 데이터 파일을 읽는다고 나와있어요

다만 하나의 트랜잭션 내에서 row lock 이 걸렸을때 어떠한 격리 레벨에 상관없이(언커밋 포함) 변경 이전 데이터가 조회되는 현상이 있었습니다.

그림은 READ_COMMIT 과 REPEATABLE_READ 만 해당함에 동의 합니다.
