### ISSUE TITLE
논리적인 주소? 레코드의 주소 값?

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#54]
99p에 보면
> InnoDB의 모든 테이블의 모든 세컨더리 인덱스는 레코드의 주소 대신 프라이머리 키의 값을 논리적인 주소로 사용한다.  MyISAM 테이블의 프라이머리 키를 포함한 모든 인덱스는 물리적인 레코드의 주소 값(ROWID) 을 가진다.

여기서 논리적인 주소와 물리적인 레코드의 주소값의 차이가 뭘까요?
나중에 나올려나.. ㅠ

**Comment by hongji3354** [comment]
물리적인 주소는 데이터 파일에 저장되어 있는 실제 레코드 주소를 의미하고
 논리적인 주소는 실제 레코드의 주소를 알고 있는 주소를 의미하는 것 같네요.

MylSAM 테이블에 레코드는 프라이머리 키 값과 무관하게 INSERT되는 순서대로 데이터 파일에 저장된다. 그리고 MylSAM 테이블에 저장되는 레코드는 모두 ROWID 라는 물리적인 주소값을 가지는 데, 프라이머리 키와 세컨더리 인덱스는 모두 데이터 파일에 저장된 레코드의 ROWID 값을 포인터로 가진다.
> Real MySQL p.145
