### ISSUE TITLE
InnoDB 스토리지 엔진과 리두로그 파일

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#55]
p.112를 보면 InnoDB 스토리지 엔진과 리두로그 파일에 대한 관계(?)가 나오는지 무슨말인지 전혀 모르겠네요.
혹시 아시는분~~

![image](https://user-images.githubusercontent.com/57903576/168222318-196c98ce-8314-4d4f-a0e9-3e6402bacb9d.png)

**Comment by pjhsk113** [comment]
InnoDB 버퍼 풀의 성능 향상을 위한 용도로 데이터 캐시와 버퍼링 기능이 있는데,
이중 리두 로그 파일은 버퍼링 기능에 영향을 주는 녀석입니다.
이녀석의 동작을 제가 이해한 내용으로 요약해보면 다음과 같습니당.

1. InnoDB 버퍼 풀은 클린 페이지와 더티 페이지(변경된 데이터)를 가진다.

2. 더티 페이지는 언젠가 디스크에 기록되어야 한다.

3. 한정된 메모리 공간인 버퍼 풀에 더티 페이지가 계속 머무를 수 없으므로 리두 로그 파일과의 순환 고리를 이용해 데이터 변경을 기록한다.

4. 리두 로그 파일에 데이터 변경이 기록될 때마다 LSN이라는 시퀀스 번호를 증가시킨다.

5. InnoDB 스토리지 엔진은 주기적으로 체크포인트 이벤트를 발생시켜 그 시점의 리두 로그 파일의 LSN을 시작점으로 삼는다.(마지막 LSN은 계속 증가하며 데이터 변경을 기록)

6. 체크포인트가 발생하면 LSN 시작점부터 그보다 작은 LSN을 가진 리두 로그 엔트리와 관련된 버퍼 풀의 더티 페이지를 디스크로 동기화한다.

InnoDB 버퍼 풀과 리두 로그 파일의 관계가 중요하다고 하는 이유는
리두 로그 파일의 크기에 따라 InnoDB 스토리지 엔진이 변경된 내용을 적절하게 버퍼 풀에 모을 수 있고, 디스크에 부드럽게 기록될 수 있기 때문인 것 같습니다.
