### ISSUE TITLE
세컨더리 인덱스의 크기와 클러스터링 인덱스의 크기

### ISSUE THREAD

**Issue by hongji3354** [java-starter/ReadingBooks#56]
p.275의 8.8.4.1 클러스터링 인덱스 키의 크기를 보면 프라이머리 키의 크기가 커지면 세컨더리 인덱스도 자동으로 크기가 커진다고 되어 있습니다. 근데 세컨더리 인덱스의 경우 그냥 프라이머리 키를 참조(?) 하는 것만으로 아는데 둘 사이에 어떤 연관관계가 있어서 프라이머리 키가 커지면 세컨더리 인덱스도 커진다고 하는 걸까요?

**Comment by pjhsk113** [comment]
세컨더리 인덱스는 다음과 같은 순서로 레코드를 가져오게 됩니다.
1. 세컨더리 인덱스 검색
2. 세컨더리 인덱스에 저장되어 있는 프라이머리 키 값을 찾음
3. 찾은 프라이머리 키 값으로 프라이머리 키 인덱스를 검색해 해당 리프 노드의 레코드를 가져옴

모든 세컨더리 인덱스는 위와 같이 프라이머리 키를 이용해 레코드를 가져와야 하기 때문에 
반드시 프라이머리 키를 가지고 있습니다.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/32737230/177580056-d52dc36f-7ee6-47ea-9e0b-3f7358f72347.png">

인덱스 페이지의 구조를 보면 키 값과 노드 주소를 가지고 있어요. 
이 둘은 각각 크기를 가지고 있고, 키 값과 노드 주소 크기에 따라 인덱스 페이지의 크기가 결정됩니다.

모든 세컨더리 인덱스는 프라이머리 키를 가지고 있으니 프라이머리 키 값이 커지면 당연히 노드 주소를 저장하는 공간도 커지겠죠??
따라서 프라이머리 키의 크기가 커지면 세컨더리 인덱스의 크기도 자동으로 커진다고 볼 수 있을 것 같습니다.

**Comment by hongji3354** [comment]
음...프라이머리 키를 가지고 있는 인덱스 페이지의 크기가 커지는 것이지 프라이머리 키 주소(자식노드주소)의 크기는 유지 아닌가요?

**Comment by pjhsk113** [comment]
세컨더리 인덱스의 노드 주소에는 프라이머리 키 값이 담기니까 
프라이머리 키 값이 커지면 세컨더리 인덱스의 인덱스 페이지도 함께 커지게 됩니다.
