### ISSUE TITLE
의존성의 대칭적? 비대칭적?

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#58]
<img width="907" alt="스크린샷 2023-01-29 오후 3 00 46" src="https://user-images.githubusercontent.com/27226273/215308098-367c9ae1-fddc-4879-9cde-3c8518acf680.png">

대칭적? 비대칭적? 무슨 의미인지 더 명확하게 알고싶어요

**Comment by pjhsk113** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/32737230/215310697-bf8edbcf-339e-4a86-bf7c-5990538bc7b2.png">

위 그림에서 의존성의 방향(화살표)은 대칭적 구조를 가지고있죠
계층형에서는 의존성이 한쪽으로만 흐르니 비대칭적이라고 표현한거 같네요

**Comment by hongji3354** [comment]
저도 장호님과 같은 의견입니다:)
