### ISSUE TITLE
도메인 로직을 먼저 구현했다면 어떤식으로 했을까요?

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#59]
<img width="920" alt="스크린샷 2023-01-29 오후 3 02 32" src="https://user-images.githubusercontent.com/27226273/215308176-7657f5b3-3cd2-43c8-85e5-359d84f6a6cb.png">

데이터베이스 설계가아닌 도메인 로직을 먼저 만든다라는 방법은 어떤 방법일까요?

예를 들면 주문 도메인이 있다고 하면,
주문 상태의 관련된 도메인을 먼저 만들텐데, 어떤식으로 만들어가는지 궁금하네요

**Comment by hongji3354** [comment]
우리가 전통적으로 하던 테이블 설계 후 도메인 매핑하는 과정을 바꾸면 되지 않을까요?
도메인을 먼저 설계한 뒤 영속성 코드와 매핑하는 걸로 가는 거죠.

예를들어 주문 상태 관련 도메인이 있다면 행위를 구현한 뒤 행위에 필요한 필드를 만들고, 도메인 객체를 사용해서 비즈니스 로직을 모두 구현한 뒤 영속성 코드와 매핑을 하는 거죠.

**Comment by jiseok-choi** [comment]
도메인 로직을 우선 구현하는 방법은 여러가지가 있는데 
DDD 방법론 중에서 한가지 구체적인 방법으로 거론되는 이벤트 스토밍 방식을 소개해 볼 수 있을거 같네요

도메인 로직을 먼저 만들기 위한 방법으로 시스템에서 발생하는 이벤트를 추출하는 것부터 시작해서
최종적으로 도메인 로직을 구체화 시키는 방법이 있다고 합니다.

흥미로웠던 점은 도메인에 관련된 다방면의 이해관계자들이 모여서 진행한다는 점 입니다.
DB 를 기준으로 도메인을 정립해나가던 기존의 방식에서의 명확한 차이점이 보이는 부분이라고 생각합니다.

https://www.msaschool.io/operation/design/design-three/

**Comment by DaeAkin** [comment]
https://www.youtube.com/watch?v=hUcpv5fdCIk&ab_channel=OpenUP-%EC%98%A4%ED%94%88%EC%97%85
