### ISSUE TITLE
클래스 네이밍

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#60]
<img width="915" alt="스크린샷 2023-01-29 오후 3 04 56" src="https://user-images.githubusercontent.com/27226273/215308263-e943c8c8-bdec-46f7-a58b-482f42f24799.png">

저라면 **UserCreateService(상태)**라고 지었을거 같은데, **RegisterUserService(행동)** 라고 지었네요

네이밍에도 개발자가 행동기반으로 생각하는지 상태기반으로 생각하는지에따라 많이 달라질것 같네요
RegisterUserService라는 네이밍 좀 괜찮은듯

**Comment by hongji3354** [comment]
이건 DDD에서 말하는 것 처럼 회사 및 팀에서 용어를 어떻게 사용하고 있냐가 중요할 것 같네요.
그리고 Service라는 네이밍 보다 Command나 Query가 좋은 것 같아요. 시스템 입장에서 행위가 더 명확하게 보여서요. 예를들어 UserRegisterCommand, UserDetailInfoQuery 같은 형태요ㅋㅋㅋ
