### ISSUE TITLE
6p - 테스트하기 어려워진다

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#61]
전통적인 3계층의 단점의 하나로 테스트하기 어려워진다고 나와있는데,
예제로 웹 계층에서 영속성 계층을 바로 접근할 경우를 가정을 했네요 
문제점1

> 하나의 필드를 조작하는 것에 불과하더라도 도메인 로직을 웹 계층에 구현하게 된다.

웹 계층이 아니라 영속성 계층에서 구현하지 않나..?

문제점 2

> 웹 계층 테스트에서 도메인 계층뿐만 아니라 영속성 계층도 모킹해야 한다.

두 문제점 다 헥사고날 아키텍처를 사용하면 해결가능한 문제인가 싶네요..

**Comment by pjhsk113** [comment]
문제점1
원래라면 웹 계층 -> 도메인 계층 -> 영속성 계층 순으로 의존성 흐름을 가지고, 
도메인 계층에서 영속성 계층의 필드 조작 로직을 호출하는 방식으로 구현될텐데유

이를 뛰어넘어 웹 계층 -> 영속성 계층을 호출하면 영속성 계층에 구현 되어있는 필드 조작에 대한 로직을 웹 계층에서 호출 및 구현해야하니 의존성이 생기게되져

문제점2
이 책은 더 나은 소프트웨어 아키텍쳐를 제시하는 책입니다. 
계층형 아키텍쳐가 가지고 있는 단점을 소개하는 부분이 당연히 들어있어야 이 책을 쓰는 근거가 되기 때문에 
> 두 문제점 다 헥사고날 아키텍처를 사용하면 해결가능한 문제인가 싶네요..

이건 당연한 거라고 생각해요~

**Comment by hongji3354** [comment]
올려주신 두 문제는 Layer Architecture의 문제가 아닌 약속의 문제라고 생각해요. 
이건 어떤 아키텍처를 사용하던 간에 중간 구멍을 만들게 되면 다 문제가 생기게 되죠:)

결국 다음의 트윗처럼 디자인을 우회하는 곳이라면 다 발생하는 문제라 생각합니다~
https://twitter.com/sm_park/status/1595312796774064128
