### ISSUE TITLE
"유스케이스" 의 의미

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#62]
책에서 유스케이스 라는 단어가 자주 등장하는데, 
제가 생각할땐 Service의 역할의 느낌이 강하게 드는데 맞나여?

**Comment by hongji3354** [comment]
Client 입장에서 볼 때 제공해주는 기능 하나하나가 유스케이스라고 생각합니다. 예를들어 우리의 Application이 배송 시스템이라고 할 때 Client가 웹 어댑터(primary adapter)일 경우 제공해야하는 유스케이스는 배송 신청, 배송 조회, 배송 취소가 되겠네요. 

이제 Client가 우리의 Application 일 때(Secondary Adapter)는 다른 배송사의 배송 신청, 배송 조회, 배송 취소가 유스케이스 됩니다:)
