### ISSUE TITLE
JpaRepository를 상속한 인터페이스 클래스는 어디에 속해야 할까요?

### ISSUE THREAD

**Issue by DaeAkin** [java-starter/ReadingBooks#63]
JpaRepository는 spring-jpa 자원인데, 어느 패키지에 속해야 하는게 맞을까요?

**Comment by hongji3354** [comment]
헥사고날 아키텍쳐 취지로 본다면 영속성 어댑터에 위치하는게 맞지만 그러면 유스케이스에서 JpaRepository에 있는 메소드들 사용을 못하니 어쩔 수 없이 출력 포트 패키지에 속해야 할 것 같습니다. 근데 완전히 헥사고날 아키텍처를 추구한다면 JpaRepository를 안쓰는 게 맞는 것 같습니다.

![image](https://user-images.githubusercontent.com/57903576/216812265-c049f53d-be1c-4534-ae8e-13256aac21cf.png)
